var Maker = {

	/**
	 * Make a thing that could be a tableid, a table, or a string
	 * @param  {string} options.type  tableid, table, or string
	 * @param  {Object|string} options.value the thing
	 * @param  {Table} Table         the table schema
	 * @return {string}              the random value
	 */
	makeMixedThing: async function(thing, Table){
		if(typeof thing === "string") 
			return thing;

		var {type, value} = thing;
		if(type === undefined || value === undefined || value === null)
			return value;

		switch(type){
			case "table_id":
				var table = await Table.findById(value); // TODO
				return await table.roll();
				break;
			case "table":
				var table = new Table(value);
				return await table.roll(); // TODO: roll
				break;
		}
		return value;
	},

	/**
	 * Creates a random version of a generator
	 * @param  {Generator} gen         the generator
	 * @param  {Integer} generations the number of nested levels to generate
	 * @param  {BuiltPack} builtpack        the compiled built pack with combined definitions of generators to use
	 * @param {Object} node the pre-existing node that we are generating children for
	 * @return {Object}             the node that will be passed to the user
	 */
	make: async function(gen, generations, builtpack, node){
		if(!gen){
			console.trace("gen cannot be undefined");
			throw new Error("make(): gen cannot be undefined");
		}

		if(isNaN(generations) || generations < 0) generations = 0;

		//make into a Generator obj if not
		if(!gen.save){
			var Generator = builtpack.model('Generator');
			gen = new Generator(gen);
		}

		//extends
		if(gen.extends){
			var extendsGen = new Generator(builtpack.generators[gen.extends])
			extendsGen.set(gen);
			gen = extendsGen;
		}

		// make a new node if doesn't exist yet
		if(!node){
			node = {
				up: [] // placeholder for later
			};
			//optional fields, if new -----------------------------

			var name = await gen.makeName;
			var style = await gen.makeStyle;
			node = Object.assign({}, node, style);
			if(name) node.name = name;
			if(gen.isa) node.isa = gen.isa;
			if(gen.in && gen.in.length) node.in = true; // placeholder for later;
		}
		
		// in ---------------------------------------------
		if(generations && gen.in && gen.in.length){
			var madeChildren;

			await Promise.all(gen.in.map((c)=>{
				return this.makeChild(c, builtpack, generations-1);
			})).then(result=>madeChildren=result);

			//flatten madeChildren into single array
			var flatArray = [];
			madeChildren.forEach((child)=>{
				if(child instanceof Array){
					flatArray = flatArray.concat(child);
				}
				else if(child){
					flatArray.push(child);
				}
			});

			node.in = flatArray;

			if(!madeChildren || madeChildren.length === 0){
				node.isEmpty = true;
			}
		}

		return node;
	},

	/**
	 * Processes the type of a child to randomly generate it
	 * @param  {Object} child       childSchema
	 * @param  {BuiltPack} builtpack   the compiled pack
	 * @param  {Integer} generations the number of nested levels to generate
	 * @return {Object[]}             an array of nodes that was generated by this child
	 */
	makeChild: async function(child, builtpack, generations){
		var Table = builtpack.model('Table');
		var Maker = this;

		// check chance
		if(!child.isIncluded) return null;


		const amount = child.makeAmount;
		
		var {gen,table} = await checkTypes(child, Table, builtpack);

		var arr = await makeAmount(gen, table, child.value, amount);

		return arr;

		async function makeAmount(gen, table, value, amount){
			var arr = [];
			for(var i = 0; i < amount; i++){
				if(gen){
					arr.push(await Maker.make(gen, generations, builtpack))
				}
				else if(table){
					var result = await table.roll();
					if(typeof result === undefined){
						continue;
					}
					var { gen: newGen, table: newTable } = await checkTypes(result, Table, builtpack);
					arr = arr.concat(await makeAmount(newGen, newTable, result, 1));
				}
				else if(value){
					arr.push({ 
						name: value,
						up: [],
						in: false
					});
				}
			}
			return arr;
		}
	}
}

async function checkTypes(child, Table, builtpack){
	var gen, table; 

	if(child.type === "table"){
		table = new Table(child.value)
	}
	else if(child.type === "table_id"){
		table = await Table.findById(child.value)
	}
	else if(child.type === "generator"){
		gen = builtpack.generators[child.value]
	}
	else if(child.type === "embed"){
		gen = child.value;
	}
	return {gen, table};
}

module.exports = Maker;